# Introdução ao Numpy

O principal objeto NumPy é um array multi-dimensional homogeneo (**ndarray**). É uma tabela de elementos (usualmente números), no qual todos os elementos possuem o mesmo tipo indexados por uma tupla de inteiros não negativos. Em numpy, as dimensões são chamadas de **axis**

In [7]:
!pip install numpy

In [8]:
import numpy as np

## 1. Criando Arrays

* np.array()
* np.zeros()
* np.ones()
* np.empty()
* np.eye()
* np.asarray()
* np.arange()
* np.linspace()

### 1.1 np.array()

In [9]:
a = np.array([1,2,3,4,5,6]) #cria um ndaaray de uma dimensão
print(f'Array de uma dimensão: \n{a}')

Array de uma dimensão: 
[1 2 3 4 5 6]


In [10]:
#cria um array de 2 dimensões
b = np.array([[1, 2, 3],
             [4, 5, 6]])
print(f'Array com multiplas dimensões: \n {b}')

Array com multiplas dimensões: 
 [[1 2 3]
 [4 5 6]]


### 1.2 np.zeros(), np.ones(), np.empty()

Esses métodos são utilizados para criação de arrays como **placeholders** (i.e., que serão prenchidos). Para isso, precisamos informar apenas o formato desejado. Esses métodos evitam a necessidade de aumentar as dimensões dos arrays de forma dinâmica, a qual é uma operação custosa.

Portanto, **np.zeros(shape=(m,n))** cria um array de mxn preenchidos com 0, enquanto **np.ones()** preenche o array com 1. Por fim, **np.empty()** preenche o array com valores aleatórios. É importante destacar que o dtype padrão é float64.

In [11]:
c = np.zeros((2, 2))
print(f"Array preenchidos com zero's: \n {c}")

Array preenchidos com zero's: 
 [[0. 0.]
 [0. 0.]]


In [12]:
d = np.ones((2, 2))
print(f"Array preenchidos com um's: \n {d}")

Array preenchidos com um's: 
 [[1. 1.]
 [1. 1.]]


In [13]:
e = np.empty((4, 3))
print(f"Array com valores aleatórios: \n {e}")

Array com valores aleatórios: 
 [[1.09041773e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.08858384e-311 4.42969710e+175]
 [1.38321358e-047 5.69617335e-066 1.11644974e+165]
 [5.40243918e-038 7.12630656e-067 5.15972318e-066]]


### 1.3 np.eye()

Cria um ndarray com 1s apenas na diagonal principal

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 1.4 np.asarray()
Converte a entrada em um ndarray

In [15]:
f = np.asarray([1, 2, 3, 4, 5, 6])
print(f'Array de uma dimensão: \n{f}')

Array de uma dimensão: 
[1 2 3 4 5 6]


### 1.5 diferença entre np.array() e np.asarray()

A diferença principal é que o np.array() por padrão cria uma cópia do objeto, enquanto o np.asarray() não cria esta cópia.

In [17]:
a = np.array([1, 2], dtype=np.float32)

print(f"Dados não alterados {np.array(a, dtype=np.float32) is a}")
print(f"Dados alterados {np.array(a, dtype=np.float64) is a}")
print(f"Dados não alterados {np.asarray(a, dtype=np.float32) is a}")
print(f"Dados alterados {np.asarray(a, dtype=np.float64) is a}")

Dados não alterados False
Dados alterados False
Dados não alterados True
Dados alterados False


### 1.6 np.arange()

Este método é utilizado para criar ndarrays com valores dentro de um intervalo definido:
* np.arange(start, stop, step)
    * **start**: valor inicial do intervalo
    * **stop**: valor final do intervalo
    * **step**: espaçamento entre os valores do intervalo

In [18]:
g = np.arange(10, 30, 5)
print(f'O array criado foi: \n{g}')

O array criado foi: 
[10 15 20 25]


### 1.7 np.linspace()

retorna uma sequencia igualmente espaçada baseado em um intervalo
* np.linspace(start, stop, num=50)

In [19]:
h = np.linspace(0, 10, 3)
print(f'O array criado foi: \n{h}')

O array criado foi: 
[ 0.  5. 10.]


## 2. Atributos Importantes de um ndarray

* ndarray.dim
    * representa o número de dimensões do array
* ndarray.shape
    * representa o formato do array
* ndarray.size
    * representa a quantidade total de elementos no array
* ndarray.dtype
    * representa o tipo dos elementos do array
* ndarray.itemsize
    * representa o tamanho em bytes dos elementos do array
* ndarray.data
    * representa os elementos do array.

In [20]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]
            ])
a.shape

(3, 2)

In [21]:
a.size

6

In [24]:
a.ndim

2

In [25]:
a.dtype

dtype('int64')

## 3. Indexando, Fatiando e Iterando arrays

ndarrays podem ser indexados, fatiados (i.e., slicing) e iterados, da mesma forma que as listas em python

### 3.1 Indexando arrays

In [26]:
a = np.array([[1, 2],
              [3, 4]
             ])
#a[l][c] l é a linha e c1 a coluna, respectivamente
b = a[1][0]
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[[1 2]
 [3 4]]
b: 
3


### 3.2 Fatiando arrays (Slicing)

In [27]:
a = np.arange(20)
print(a[2:10:2])
print(a[2:10])
print(a[1])
print(a[2:])

[2 4 6 8]
[2 3 4 5 6 7 8 9]
1
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 4. Alterando o Formato do Array (reshaping)

altera o formato (i.e., shape) do array sem alterar os dados
* np.reshape(a, newshape)

In [28]:
a = np.arange(6)
b = a.reshape(2,3)
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[0 1 2 3 4 5]
b: 
[[0 1 2]
 [3 4 5]]


## 5. Broadcasting

O termo *broadcasting* descreve como o NumPy trata arrays com formas diferentes durante operações aritméticas. Sujeito a certas restrições, a matriz menor é “transmitida” pela matriz maior para que tenham formas compatíveis. Broadcasting fornece um meio de vetorizar operações de matriz para que o loop ocorra em C em vez de Python. Ele faz isso sem fazer cópias desnecessárias de dados e geralmente leva a implementações de algoritmo eficientes. Há, no entanto, casos em que a transmissão é uma má ideia porque leva ao uso ineficiente da memória que retarda a computação.

As operações NumPy geralmente são feitas em pares de arrays elemento por elemento. No caso mais simples, os dois arrays devem ter exatamente a mesma forma, como no exemplo a seguir:

In [29]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

A regra de transmissão do NumPy relaxa essa restrição quando as formas das matrizes atendem a certas restrições. O exemplo de transmissão mais simples ocorre quando uma matriz e um valor escalar são combinados em uma operação:

In [31]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

![image.png](attachment:image.png)

Ao operar em dois arrays, o NumPy compara suas formas elementarmente. Ele começa com a dimensão à direita (ou seja, mais à direita) e segue para a esquerda. Duas dimensões são compatíveis quando

* são iguais ou
* um deles é 1.

Se essas condições não forem atendidas, uma exceção **ValueError: os operandos não puderam ser transmitidos será lançada, indicando que as matrizes têm formas incompatíveis.**

os arrays de entrada não precisam ter o mesmo número de dimensões. O arrays resultante terá o mesmo número de dimensões que o array de entrada com o maior número de dimensões, onde o tamanho de cada dimensão é o maior tamanho da dimensão correspondente entre os arrays de entrada. Observe que as dimensões ausentes são consideradas de tamanho um.

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a.shape)
print(b.shape)

(3, 3)
(3,)


In [33]:
#Exemplo stretch
np.array([b, b, b])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
c = a + b
print(f'a: \n {a}')
print(f'broadcasting c: \n {c}')

a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasting c: 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## 6. Funções comuns do NumPy

### 6.1 ndarray.flat()

utilizado para "vetorizar" um array de múltiplas dimensões

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'a: \n {a}')
print(f'a flat: \n {a.flat[:]}')

a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
a flat: 
 [1 2 3 4 5 6 7 8 9]


### 6.2 ndarray.transpose()

faz a transposição dos eixos do array

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 6.3 np.concatenate(a1, a2, axis)

Concatena uma sequencia de arrays baseado no axis especificado

In [41]:
a = np.arange(6).reshape(2, 3)
b = np.arange(8, 14).reshape(2, 3)
print(f'a: \n{a}')
print(f'b: \n{b}')

a: 
[[0 1 2]
 [3 4 5]]
b: 
[[ 8  9 10]
 [11 12 13]]


In [42]:
np.concatenate((a, b), axis=0) #nas linhas

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 8,  9, 10],
       [11, 12, 13]])

In [43]:
np.concatenate((a, b), axis=1) #adiciona nas colunas

array([[ 0,  1,  2,  8,  9, 10],
       [ 3,  4,  5, 11, 12, 13]])

### 6.4 np.append()

Adiciona valores no final do array, como o .append() das listas em python

In [44]:
a = np.array([[1,2,3] , [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis=0) #axis especifica em qual dimensão
c = np.append(a, [[7, 8, 9]])

print(f'b: \n {b}')
print(f'c: \n {c}')

b: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
c: 
 [1 2 3 4 5 6 7 8 9]


### 6.5 np.insert()

Podemos inserir valores baseado em um axis e um indice
* np.insert(arr, idx, values, axis)

In [45]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
np.insert(a, 2, [7, 8])

array([0, 1, 7, 8, 2, 3, 4, 5])

In [51]:
np.insert(a, 2, [7, 8], axis=1)

array([[0, 1, 7, 2],
       [3, 4, 8, 5]])

### 6.6 np.delete()

retorna um novo array sem a linha ou a coluna informada

In [57]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.delete(a, 0, axis=1) #remove linha 0

array([[1, 2],
       [4, 5]])

In [55]:
np.delete(a, 0, axis=0)  #remove coluna 0

array([[3, 4, 5]])

## 7. Operações Aritméticas

* soma
* subtração
* multiplicação
* divisão
* soma acumulada (cumsum)
* dot (multiplicação de matrizes)


In [59]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
b = np.arange(10, 16).reshape(2, 3)
b

array([[10, 11, 12],
       [13, 14, 15]])

### 7.1 Soma

In [61]:
print(np.add(a, b))
print(f' np.add(a, b) == a + b: \n {np.add(a, b) == a + b}')

[[10 12 14]
 [16 18 20]]
 np.add(a, b) == a + b: 
 [[ True  True  True]
 [ True  True  True]]


### 7.2 Subtração

In [62]:
b - a

array([[10, 10, 10],
       [10, 10, 10]])

### 7.3 Multiplicação

In [63]:
a * b

array([[ 0, 11, 24],
       [39, 56, 75]])

### 7.4 Divisão

In [64]:
a / b

array([[0.        , 0.09090909, 0.16666667],
       [0.23076923, 0.28571429, 0.33333333]])

### 7.5 Soma Acumulada (cumsum)

Retorna um novo vetor no qual a posição i do array tem seu valor substituído pela soma do valor na posição i com todos os valores i-1 anteriores do array **original**.

e.g. a soma cumulativa do array:

```
arr = np.array([0, 1, 2, 3])
```

seria ```[0 1 3 6]```


In [65]:
arr = np.array([2, 3, 4, 5, 6, 7, 8])
print(np.cumsum(arr))
print(arr)

[ 2  5  9 14 20 27 35]
[2 3 4 5 6 7 8]


### 7.6 Dot (multiplicação de matrizes)

In [66]:
np.dot(a, b) #aqui dá um erro mesmo devido a a e b terem mesmas dimensões

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [67]:
np.dot(a, b.T)

array([[ 35,  44],
       [134, 170]])

In [68]:
a@b.T

array([[ 35,  44],
       [134, 170]])

## 8. Operações de Agregação

* np.sum()
* np.mean()
* np.std()
* np.var()

In [69]:
array_gigante = np.random.randint(0, 1000, size=1_000_000)

In [70]:
%timeit sum(array_gigante)
%timeit np.sum(array_gigante)

41.5 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
419 μs ± 4.84 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### 8.1 np.sum()

In [71]:
np.sum(array_gigante)

np.int64(499513722)

### 8.2 np.mean()

In [72]:
np.mean(array_gigante)

np.float64(499.513722)

### 8.3 np.std()

In [73]:
np.std(array_gigante)

np.float64(288.6906800499571)

### 8.4 np.var()

In [74]:
np.var(array_gigante)

np.float64(83342.30874770669)

### 8.5 np.max()

In [75]:
np.max(array_gigante)

np.int32(999)

### 8.6 np.min()

In [76]:
np.min(array_gigante)

np.int32(0)

## 9. Agregação com múltiplas dimensões

podemos utilizar o axis para fazer diferentes agregações

![image-3.png](attachment:image-3.png)

In [77]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

### 9.1 sem axis

In [78]:
np.sum(a)

np.int64(15)

### 9.2 axis=0

In [79]:
np.sum(a, axis=0)

array([3, 5, 7])

### 9.3 axis=1

In [80]:
np.sum(a, axis=1)

array([ 3, 12])