In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import KFold

# Carregar o conjunto de dados Wine
data = load_wine()
X = data.data
y = data.target

# Definir configurações
k_values = [3, 5, 7]  # Valores de k para k-NN
preprocessing_strategies = ['sem_escalonamento', 'com_escalonamento']
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Função para realizar experimentos
def run_experiment(classifier, X, y, classifier_name, preprocessing):
    # Validação cruzada para acurácia
    scores = cross_val_score(classifier, X, y, cv=kf, scoring='accuracy')
    # Previsões para matriz de confusão
    y_pred = cross_val_predict(classifier, X, y, cv=kf)
    # Matriz de confusão
    cm = confusion_matrix(y, y_pred)
    # Relatório de classificação
    report = classification_report(y, y_pred, output_dict=True)
    
    # Imprimir resultados
    print(f"\n📊 {classifier_name} ({preprocessing})")
    print(f"Acurácia média: {scores.mean():.4f} ± {scores.std():.4f} ✅")
    print("Matriz de Confusão:")
    print(cm)
    print("\nMétricas por classe:")
    for cls in report:
        if cls.isdigit():
            print(f"Classe {cls}: Precisão={report[cls]['precision']:.4f}, "
                  f"Recall={report[cls]['recall']:.4f}, "
                  f"F1-Score={report[cls]['f1-score']:.4f} 🌟")
    print(f"Macro F1-Score: {report['macro avg']['f1-score']:.4f} 🎯")

# Experimentos
for preprocessing in preprocessing_strategies:
    # Preparar dados
    if preprocessing == 'com_escalonamento':
        scaler = StandardScaler()
        X_processed = scaler.fit_transform(X)
    else:
        X_processed = X
    
    # k-NN para diferentes valores de k
    for k in k_values:
        knn = KNeighborsClassifier(n_neighbors=k)
        run_experiment(knn, X_processed, y, f"k-NN (k={k})", preprocessing)
    
    # Naive Bayes
    nb = GaussianNB()
    run_experiment(nb, X_processed, y, "Naive Bayes", preprocessing)


📊 k-NN (k=3) (sem_escalonamento)
Acurácia média: 0.7036 ± 0.1392 ✅
Matriz de Confusão:
[[51  3  5]
 [ 7 48 16]
 [ 8 14 26]]

Métricas por classe:
Classe 0: Precisão=0.7727, Recall=0.8644, F1-Score=0.8160 🌟
Classe 1: Precisão=0.7385, Recall=0.6761, F1-Score=0.7059 🌟
Classe 2: Precisão=0.5532, Recall=0.5417, F1-Score=0.5474 🌟
Macro F1-Score: 0.6898 🎯

📊 k-NN (k=5) (sem_escalonamento)
Acurácia média: 0.6641 ± 0.1001 ✅
Matriz de Confusão:
[[53  1  5]
 [ 5 47 19]
 [ 6 24 18]]

Métricas por classe:
Classe 0: Precisão=0.8281, Recall=0.8983, F1-Score=0.8618 🌟
Classe 1: Precisão=0.6528, Recall=0.6620, F1-Score=0.6573 🌟
Classe 2: Precisão=0.4286, Recall=0.3750, F1-Score=0.4000 🌟
Macro F1-Score: 0.6397 🎯

📊 k-NN (k=7) (sem_escalonamento)
Acurácia média: 0.6588 ± 0.1007 ✅
Matriz de Confusão:
[[53  0  6]
 [ 6 46 19]
 [ 7 23 18]]

Métricas por classe:
Classe 0: Precisão=0.8030, Recall=0.8983, F1-Score=0.8480 🌟
Classe 1: Precisão=0.6667, Recall=0.6479, F1-Score=0.6571 🌟
Classe 2: Precisão=0.4186, Re