(2,5pt) A base de dados apresentada na Tabela 1 contém amostras de dados de 14 pessoas avaliadas em uma clínica. Cada amostra desta base, que pode ser de um paciente doente ou não (classes 𝐶𝑖 do problema), possui quatro atributos: todos já discretizados por especialistas. Suponha que um novo paciente jovem (x) chegue na clínica apresentando nível médio da substância A no sangue, nível baixo da substância B no sangue e possua histórico familiar da doença. A qual classe do problema um classificador Naive Bayes atribuiria o paciente x? Apresente todos os cálculos realizados para chegar à sua conclusão. 

In [ ]:
import pandas as pd

# Dados da Tabela 1
dados = pd.DataFrame([
    ['Jovem', 'Alto',  'Baixo', 'Não', 'Não'],
    ['Jovem', 'Alto',  'Alto',  'Não', 'Não'],
    ['Adulto','Alto',  'Baixo', 'Não', 'Não'],
    ['Idoso', 'Médio', 'Baixo', 'Não', 'Não'],
    ['Idoso', 'Baixo', 'Baixo', 'Sim', 'Não'],
    ['Idoso', 'Baixo', 'Alto',  'Sim', 'Não'],
    ['Adulto','Baixo', 'Alto',  'Sim', 'Não'],
    ['Jovem', 'Médio', 'Baixo', 'Não', 'Não'],
    ['Jovem', 'Baixo', 'Baixo', 'Sim', 'Sim'],
    ['Idoso', 'Médio', 'Baixo', 'Sim', 'Não'],
    ['Jovem', 'Médio', 'Alto',  'Sim', 'Não'],
    ['Adulto','Médio', 'Alto',  'Não', 'Não'],
    ['Adulto','Alto',  'Baixo', 'Sim', 'Não'],
    ['Idoso', 'Médio', 'Alto',  'Não', 'Sim'],
], columns=['Idade', 'A', 'B', 'Hist', 'Classe'])

In [ ]:
# Novo paciente
x = {'Idade': 'Jovem', 'A': 'Médio', 'B': 'Baixo', 'Hist': 'Sim'}

# Função para calcular P(Classe) * P(x1|Classe) * ... * P(xn|Classe)
def calcular_prob_naive_bayes(df, x):
    total = len(df)
    resultados = {}
    
    for classe in df['Classe'].unique():
        df_classe = df[df['Classe'] == classe]
        prob_classe = len(df_classe) / total
        prob_atributos = 1.0
        
        for atributo, valor in x.items():
            ocorrencias = len(df_classe[df_classe[atributo] == valor])
            prob_atributo_dado_classe = ocorrencias / len(df_classe) if len(df_classe) > 0 else 0
            prob_atributos *= prob_atributo_dado_classe
        
        resultados[classe] = prob_classe * prob_atributos
        
    return resultados

# Executa o cálculo
resultado = calcular_prob_naive_bayes(dados, x)

In [ ]:
# Mostra os resultados
print("Probabilidades:")
for k, v in resultado.items():
    print(f"  P({k}|x) ≈ {v:.6f}")

# Predição final
classe_predita = max(resultado, key=resultado.get)
print(f"\nClasse predita: {classe_predita}")

In [ ]:
from collections import Counter, defaultdict

# Base de dados (Tabela 1)
dados = [
    {'Idade': 'Jovem', 'A': 'Alto',   'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Alto',   'B': 'Alto',  'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Alto',   'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Baixo',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Baixo',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Baixo',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Baixo',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Sim'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Médio',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Médio',  'B': 'Alto',  'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Alto',   'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Alto',  'Hist': 'Não', 'Classe': 'Sim'},
]

# Novo paciente
x = {'Idade': 'Jovem', 'A': 'Médio', 'B': 'Baixo', 'Hist': 'Sim'}

# Separar por classe
classes = ['Sim', 'Não']
atributos = ['Idade', 'A', 'B', 'Hist']
contagem_classes = Counter([d['Classe'] for d in dados])
total = len(dados)

# Função para calcular P(classe) * P(x1|classe) * ... * P(xn|classe)
def probabilidade_naive_bayes(x, classe):
    dados_filtrados = [d for d in dados if d['Classe'] == classe]
    total_classe = len(dados_filtrados)
    prob = contagem_classes[classe] / total
    for att in atributos:
        ocorrencias = sum(1 for d in dados_filtrados if d[att] == x[att])
        prob *= ocorrencias / total_classe if total_classe > 0 else 0
    return prob

# Cálculo para cada classe
resultados = {classe: probabilidade_naive_bayes(x, classe) for classe in classes}
classe_predita = max(resultados.items(), key=lambda item: item[1])[0]

# Mostra os resultados
print("Probabilidades:")
for k, v in resultado.items():
    print(f"  P({k}|x) ≈ {v:.6f}")

# Predição final (versão compatível com linters/tipadores)
classe_predita = max(resultado.items(), key=lambda item: item[1])[0]
print(f"\nClasse predita: {classe_predita}")



In [ ]:
# Base de dados
dados = [
    {'Idade': 'Jovem', 'A': 'Alto',   'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Alto',   'B': 'Alto',  'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Alto',   'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Baixo',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Baixo',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Baixo',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Baixo',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Sim'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Jovem', 'A': 'Médio',  'B': 'Alto',  'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Médio',  'B': 'Alto',  'Hist': 'Não', 'Classe': 'Não'},
    {'Idade': 'Adulto','A': 'Alto',   'B': 'Baixo', 'Hist': 'Sim', 'Classe': 'Não'},
    {'Idade': 'Idoso', 'A': 'Médio',  'B': 'Alto',  'Hist': 'Não', 'Classe': 'Sim'},
]

# Novo paciente
paciente = {'Idade': 'Jovem', 'A': 'Médio', 'B': 'Baixo', 'Hist': 'Sim'}

# Contar total de amostras e por classe
total = len(dados)
sim = sum(1 for d in dados if d['Classe'] == 'Sim')  # 2
nao = sum(1 for d in dados if d['Classe'] == 'Não')  # 12

# Probabilidades a priori
p_sim = sim / total  # 2/14
p_nao = nao / total  # 12/14

# Função para probabilidade condicional
def prob_cond(atributo, valor, classe):
    total_classe = sum(1 for d in dados if d['Classe'] == classe)
    contagem = sum(1 for d in dados if d['Classe'] == classe and d[atributo] == valor)
    return contagem / total_classe

# Calcular probabilidades para Sim e Não
prob_sim = p_sim
prob_nao = p_nao
for attr in ['Idade', 'A', 'B', 'Hist']:
    prob_sim *= prob_cond(attr, paciente[attr], 'Sim')
    prob_nao *= prob_cond(attr, paciente[attr], 'Não')

# Resultado
print(f"Prob Sim: {prob_sim:.6f}")
print(f"Prob Não: {prob_nao:.6f}")
print("Classe predita:", "Sim" if prob_sim > prob_nao else "Não")

In [1]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

# Dados da Tabela 1
data = {
    'Paciente': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    'Substância A': ['Sim', 'Sim', 'Não', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Sim'],
    'Substância B': ['Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Não', 'Não', 'Não'],
    'Histórico Familiar': ['Sim', 'Não', 'Sim', 'Sim', 'Não', 'Sim', 'Sim', 'Não', 'Não', 'Sim', 'Não', 'Sim', 'Não', 'Sim'],
    'Idade': [15, 21, 36, 49, 45, 30, 29, 48, 57, 33, 39, 60, 53, 38],
    'Doença': ['Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Sim', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não', 'Não']
}

df = pd.DataFrame(data)

# Função para aplicar a árvore de decisão da Figura 2 e predizer classe
def prever_doenca(row):
    # Baseado na árvore de decisão da figura:
    # 1) Se Substância A = Sim, prediz 'Não'
    if row['Substância A'] == 'Sim':
        return 'Não'
    # 2) Se Substância A = Não e Histórico Familiar = Sim, prediz 'Sim'
    if row['Substância A'] == 'Não' and row['Histórico Familiar'] == 'Sim':
        return 'Sim'
    # 3) Se Substância A = Não e Histórico Familiar = Não, prediz 'Não'
    if row['Substância A'] == 'Não' and row['Histórico Familiar'] == 'Não':
        return 'Não'
    # Caso padrão (por segurança)
    return 'Não'

# Aplicar a predição
df['Predição'] = df.apply(prever_doenca, axis=1)

# Matriz de confusão e acurácia
y_true = df['Doença']
y_pred = df['Predição']

conf_matrix = confusion_matrix(y_true, y_pred, labels=['Sim', 'Não'])
accuracy = accuracy_score(y_true, y_pred)

print('DataFrame com predições:')
print(df[['Paciente', 'Doença', 'Predição']])
print('\nMatriz de Confusão:')
print(pd.DataFrame(conf_matrix, 
                   index=['Real: Sim', 'Real: Não'], 
                   columns=['Predito: Sim', 'Predito: Não']))
print(f'\nAcurácia: {accuracy*100:.2f}%')


DataFrame com predições:
    Paciente Doença Predição
0          1    Sim      Não
1          2    Sim      Não
2          3    Sim      Sim
3          4    Sim      Sim
4          5    Sim      Não
5          6    Sim      Não
6          7    Não      Sim
7          8    Não      Não
8          9    Não      Não
9         10    Não      Sim
10        11    Não      Não
11        12    Não      Sim
12        13    Não      Não
13        14    Não      Não

Matriz de Confusão:
           Predito: Sim  Predito: Não
Real: Sim             2             4
Real: Não             3             5

Acurácia: 50.00%


In [2]:
print(f'\nAcurácia: {accuracy*100:.2f}%')



Acurácia: 50.00%


In [8]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Carregar o conjunto de dados Wine
data = load_wine()
X = data.data  # 178 amostras, 13 atributos
y = data.target  # 3 classes (0, 1, 2)

# Configurar validação cruzada com 10 pastas
kf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# Função para avaliar o modelo e coletar métricas
def evaluate_model(model, X, y, kf, scale=False):
    y_true_all = []
    y_pred_all = []
    scaler = StandardScaler() if scale else None
    
    for train_idx, test_idx in kf.split(X, y):
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        
        # Aplicar escalonamento, se necessário
        if scale:
            X_train = scaler.fit_transform(X_train)
            X_test = scaler.transform(X_test)
        
        # Treinar e prever
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        
        # Armazenar predições e rótulos verdadeiros
        y_true_all.extend(y_test)
        y_pred_all.extend(y_pred)
    
    # Calcular métricas
    cm = confusion_matrix(y_true_all, y_pred_all)
    accuracy = accuracy_score(y_true_all, y_pred_all)
    precision = precision_score(y_true_all, y_pred_all, average='macro')
    recall = recall_score(y_true_all, y_pred_all, average='macro')
    f1 = f1_score(y_true_all, y_pred_all, average='macro')
    
    return cm, accuracy, precision, recall, f1

# Configurações dos experimentos
experiments = [
    # k-NN sem escalonamento
    {'model': KNeighborsClassifier(n_neighbors=3), 'scale': False, 'name': 'k-NN (k=3, sem escalonamento)'},
    {'model': KNeighborsClassifier(n_neighbors=5), 'scale': False, 'name': 'k-NN (k=5, sem escalonamento)'},
    {'model': KNeighborsClassifier(n_neighbors=7), 'scale': False, 'name': 'k-NN (k=7, sem escalonamento)'},
    # k-NN com escalonamento
    {'model': KNeighborsClassifier(n_neighbors=3), 'scale': True, 'name': 'k-NN (k=3, com escalonamento)'},
    {'model': KNeighborsClassifier(n_neighbors=5), 'scale': True, 'name': 'k-NN (k=5, com escalonamento)'},
    {'model': KNeighborsClassifier(n_neighbors=7), 'scale': True, 'name': 'k-NN (k=7, com escalonamento)'},
    # Naive Bayes
    {'model': GaussianNB(), 'scale': False, 'name': 'Naive Bayes (sem escalonamento)'},
    {'model': GaussianNB(), 'scale': True, 'name': 'Naive Bayes (com escalonamento)'}
]

# Executar experimentos e exibir resultados
for exp in experiments:
    cm, accuracy, precision, recall, f1 = evaluate_model(exp['model'], X, y, kf, exp['scale'])
    print(f"\n=== {exp['name']} ===")
    print("Matriz de Confusão:")
    print(cm)
    print(f"Acurácia: {accuracy:.4f}")
    print(f"Precisão (macro): {precision:.4f}")
    print(f"Recall (macro): {recall:.4f}")
    print(f"F1-score (macro): {f1:.4f}")


=== k-NN (k=3, sem escalonamento) ===
Matriz de Confusão:
[[50  4  5]
 [ 8 47 16]
 [ 6 17 25]]
Acurácia: 0.6854
Precisão (macro): 0.6720
Recall (macro): 0.6768
F1-score (macro): 0.6737

=== k-NN (k=5, sem escalonamento) ===
Matriz de Confusão:
[[54  1  4]
 [ 6 47 18]
 [ 4 23 21]]
Acurácia: 0.6854
Precisão (macro): 0.6647
Recall (macro): 0.6716
F1-score (macro): 0.6672

=== k-NN (k=7, sem escalonamento) ===
Matriz de Confusão:
[[55  0  4]
 [ 6 47 18]
 [ 7 21 20]]
Acurácia: 0.6854
Precisão (macro): 0.6587
Recall (macro): 0.6703
F1-score (macro): 0.6623

=== k-NN (k=3, com escalonamento) ===
Matriz de Confusão:
[[59  0  0]
 [ 4 64  3]
 [ 0  1 47]]
Acurácia: 0.9551
Precisão (macro): 0.9537
Recall (macro): 0.9602
F1-score (macro): 0.9559

=== k-NN (k=5, com escalonamento) ===
Matriz de Confusão:
[[59  0  0]
 [ 3 66  2]
 [ 0  0 48]]
Acurácia: 0.9719
Precisão (macro): 0.9705
Recall (macro): 0.9765
F1-score (macro): 0.9728

=== k-NN (k=7, com escalonamento) ===
Matriz de Confusão:
[[59  0  0]