In [9]:
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
random.seed(42)
data = pd.read_csv('../data/vertebralcolumn-2C.csv', header=(0))

data = data.to_numpy()
nrow,ncol = data.shape
y = data[:,-1]
y = pd.get_dummies(y)
X = data[:,0:ncol-1]

p = 0.2 # fracao de elementos no conjunto de teste
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = p, random_state = 2)

print(x_train)

[[92.026308 35.392674 77.416963 56.633634 115.72353 58.057542]
 [68.832021 22.218482 50.092194 46.613539 105.985135 -3.530317]
 [58.828379 37.577873 125.742385 21.250506 135.629418 117.314683]
 ...
 [84.974132 33.021175 60.859873 51.952957 125.659534 74.333409]
 [44.318907 12.537992 36.098763 31.780915 124.115836 5.415825]
 [95.382596 24.822631 95.157633 70.559965 89.307547 57.660841]]


In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

tree_classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 101)

tree_classifier.fit(x_train, y_train)

y_pred = tree_classifier.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred, average="micro")

print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')

Acurácia: 0.7741935483870968
Precisão: 0.7741935483870968


In [16]:
from sklearn.ensemble import RandomForestClassifier

random_forest_classifier = RandomForestClassifier(n_estimators=100, random_state = 42)

random_forest_classifier.fit(x_train, y_train)

y_pred = random_forest_classifier.predict(x_test)

accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred, average="micro")
auc_curve = metrics.roc_auc_score(y_test, y_pred)

print(f'Acurácia: {accuracy}')
print(f'Precisão: {precision}')
print(f'AUC: {auc_curve}')

Acurácia: 0.8870967741935484
Precisão: 0.8870967741935484
AUC: 0.8383838383838385
