## Exercicios de Numpy

In [1]:
import numpy as np

# Criando um array
myArr = np.array([10, 20, 30, 40])

# Imprimindo o primeiro item
print(myArr[0])  # Saída: 10

10


In [ ]:
import numpy as np

# Criando um array com decimais
myArr = np.array([1.234, 5.678, 3.14159])

# Arredondando para 2 casas decimais
resultado = np.around(myArr, decimals=2)
print(resultado)  # Saída: [1.23 5.68 3.14]

[1. 6. 3.]


In [5]:
import numpy as np

# Criando o array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimindo os números [3, 4, 5]
print(arr[2:5])  # Saída: [3 4 5]

[3 4 5]


In [6]:
import numpy as np

# Criando o array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimindo os últimos 4 números
print(arr[4:])  # Saída: [4 5 6 7]

[5 6 7]


In [7]:
import numpy as np

# Criando dois arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Unindo os arrays
resultado = np.concatenate((arr1, arr2))
print(resultado)  # Saída: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [12]:
import numpy as np

# Array 1D
arr1 = np.array([1, 2, 3, 4])
print(arr1.shape)  # Saída: (4,) -> 4 elementos na única dimensão

# Array 2D
arr2 = np.array([[5,7, 6],[5,7, 6]])
print(arr2.shape)  # Saída: (3, 2) -> 3 linhas e 2 colunas

(4,)
(2, 3)


In [13]:
import numpy as np

# Criando um array
arr = np.array([1, 2, 3, 4])

# Criando uma view
view = arr[1:3]  # Pega os elementos [2, 3]

# Modificando o array original
arr[1] = 99

# A view reflete a mudança
print(view)  # Saída: [99 3]

[99  3]


In [14]:
import numpy as np

# Gerando um número aleatório de 0 a 99
numero = np.random.randint(100)
print(numero)  # Saída: um número inteiro entre 0 e 99, como 42

# Para incluir 100, use:
numero = np.random.randint(101)
print(numero)  # Saída: um número inteiro entre 0 e 100

95
64


In [15]:
import numpy as np

# Criando dois arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Somando os arrays
resultado = np.add(arr1, arr2)
print(resultado)  # Saída: [5 7 9]

[5 7 9]


In [16]:
import numpy as np

# Criando o array
arr = np.array([1, 2, 3])

# Calculando a soma cumulativa
resultado = np.cumsum(arr)
print(resultado)  # Saída: [1 3 6]

[1 3 6]


In [17]:
import numpy as np

# Criando dois arrays
arr1 = np.array([5, 6, 7])
arr2 = np.array([2, 3, 4])

# Subtraindo os arrays
resultado = np.subtract(arr1, arr2)
print(resultado)  # Saída: [3 3 3]

[3 3 3]


In [18]:
import numpy as np

# Criando um array
arr = np.array([1, 2, 3])

# Criando uma cópia
copia = arr.copy()

# Modificando o array original
arr[0] = 99

# A cópia não é afetada
print(copia)  # Saída: [1 2 3]
print(arr)    # Saída: [99 2 3]

[1 2 3]
[99  2  3]


In [19]:
import numpy as np

# Criando um array
arr = np.array([1, 2, 3, 2, 4])

# Procurando o valor 2
indices = np.where(arr == 2)
print(indices)      # Saída: (array([1, 3]),) -> índices onde 2 aparece
print(arr[indices]) # Saída: [2 2] -> valores correspondentes

(array([1, 3]),)
[2 2]


In [21]:
import numpy as np

# Gerando 100 números com distribuição normal
arr = np.random.normal(loc=50, scale=0.2, size=100)
print(arr)  # Saída: array com 100 valores próximos de 50, variando conforme o desvio padrão 0.2

[49.86164878 49.97598688 50.06984375 50.38590929 49.53908303 49.91509121
 49.79233425 49.83886048 49.92096517 49.76351164 50.18400586 50.19899426
 49.88534769 50.1179214  49.86743785 50.10883798 49.73813172 49.76566486
 49.8153048  49.85472716 49.59371174 50.21760744 49.95310028 49.95899856
 50.54441074 50.11296451 50.18796577 50.28309393 50.30917095 49.93600965
 49.98391156 50.07079164 49.86834941 49.86989146 49.84004997 49.94168549
 49.94660736 49.71350385 49.70583965 50.04524158 49.61068613 50.01040959
 50.03978123 49.70293681 49.99399836 50.11218618 50.09360456 50.0660749
 49.69179927 49.69412959 49.81382753 50.09645598 49.6807333  49.98015003
 50.38024908 50.02836778 49.79443343 50.11521614 50.1282048  49.95266551
 49.86175044 50.26761267 49.80047772 49.81169679 50.02427797 50.15404059
 49.99065473 49.92407809 50.07207054 49.8453145  49.72889158 50.25644737
 49.71604186 49.93784868 50.19983472 50.02101357 50.12921473 50.26072975
 50.06508917 49.94721498 49.99700172 50.04894179 50.

In [23]:
import numpy as np

arr = np.array([1, 4, 3, 4, 5, 4, 4])
indices = np.where(arr == 4)
valores = arr[indices]
print(valores)  # Saída: [4 4 4 4]

[4 4 4 4]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])  # Saída: [1 3 5 7]
# print(arr[1:3:5:7])  # Erro de sintaxe
# print(arr(0: step = 2))  # Erro de sintaxe

[1 3 5 7]


In [25]:
import numpy as np

# Criando um array do tipo float
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)        # Saída: [1. 2. 3. 4.]
print(arr.dtype)  # Saída: float32

[1. 2. 3. 4.]
float32


In [26]:
import numpy as np

# Criando um array
arr = np.array([1, 2, 3, 4, 5, 6])

# Separando em 3 partes
subarrays = np.array_split(arr, 3)
print(subarrays)  # Saída: [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [28]:
import numpy as np

# Criando um array com mais elementos
arr = np.array([5, 2, 9, 1, 7, 6, 3, 8, 4, 10])

# Ordenando o array (retorna uma cópia ordenada)
ordenado = np.sort(arr)
print("Array ordenado (cópia):", ordenado)  
# Saída: [1 2 3 4 5 6 7 8 9 10]

# Ordenando no lugar (modifica o array original)
arr.sort()
print("Array original após ordenação:", arr)  
# Saída: [1 2 3 4 5 6 7 8 9 10]

Array ordenado (cópia): [ 1  2  3  4  5  6  7  8  9 10]
Array original após ordenação: [ 1  2  3  4  5  6  7  8  9 10]


In [29]:
import numpy as np

# Array maior com números decimais
arr = np.array([3.5, 1.2, 4.8, 2.9, 5.1, 0.7, 9.3, 6.4, 8.2, 7.6])

# Ordenando
ordenado = np.sort(arr)
print("Array ordenado:", ordenado)
# Saída: [0.7 1.2 2.9 3.5 4.8 5.1 6.4 7.6 8.2 9.3]

Array ordenado: [0.7 1.2 2.9 3.5 4.8 5.1 6.4 7.6 8.2 9.3]


In [30]:
arr = np.array((3.5, 1.2, 4.8, 2.9, 5.1, 0.7, 9.3, 6.4, 8.2, 7.6))
print(arr)  # Saída: [3.5 1.2 4.8 2.9 5.1 0.7 9.3 6.4 8.2 7.6]

[3.5 1.2 4.8 2.9 5.1 0.7 9.3 6.4 8.2 7.6]


In [ ]:
import numpy as np

# Criando arrays com diferentes tipos de dados
arr1 = np.array([1, 2, 3])              # Inteiros
arr2 = np.array([1.5, 2.7, 3.2])        # Floats
arr3 = np.array([1, 2, 3], dtype='f')   # Float32

# Checando os tipos de dados
print(arr1.dtype)  # Saída: int64 (ou int32, dependendo da plataforma)
print(arr2.dtype)  # Saída: float64
print(arr3.dtype)  # Saída: float32

int64
float64
float32
[1 2 3]


In [33]:
import numpy as np

# Testando as opções
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array(43)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.ndim)  # Saída: 1
print(arr2.ndim)  # Saída: 0
print(arr3.ndim)  # Saída: 2
print(arr3)       # Saída: [[1 2 3]
                  #          [4 5 6]]

1
0
2
[[1 2 3]
 [4 5 6]]


In [34]:
import numpy as np

# Criando um array
arr = np.array([1, 2, 3, 4, 5])
print(arr)        # Saída: [1 2 3 4 5]
print(type(arr))  # Saída: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [35]:
import numpy as np

# Criando o array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimindo o número 8
print(arr[1, 2])  # Saída: 8

8


In [38]:
import numpy as np

# Criando arrays
arr1 = np.array([1, 2, 3, 4])              # 1D
arr2 = np.array([[1, 2], [3, 4]])         # 2D

# Checando o shape
print(arr1.shape)  # Saída: (4,)         -> 4 elementos em 1 dimensão
print(arr2.shape)  # Saída: (2, 2)       -> 2 linhas, 2 colunas

(4,)
(2, 2)
